/* bin2c: embed files as C byte arrays.
 * usage: bin2c -o out.c -p prefix file1 [file2 ...]
 * Generates:  const pf_embedded_file prefix_files[] = { {name, data, len}, ... }; size_t prefix_count;
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *basename_of(const char *p)
{
	const char *s = strrchr(p, '/');
	return s ? s + 1 : p;
}

int main(int argc, char **argv)
{
	const char *out = NULL, *prefix = "embedded";
	int first_file = 1;
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-o") && i + 1 < argc) { out = argv[++i]; first_file = i + 1; }
		else if (!strcmp(argv[i], "-p") && i + 1 < argc) { prefix = argv[++i]; first_file = i + 1; }
		else break;
	}
	if (!out || first_file >= argc) {
		fprintf(stderr, "usage: bin2c -o out.c -p prefix files...\n");
		return 2;
	}
	FILE *o = fopen(out, "w");
	if (!o) { perror(out); return 1; }
	fprintf(o, "/* generated by bin2c - do not edit */\n#include <stddef.h>\n"
	           "typedef struct { const char *name; const unsigned char *data; size_t len; } pf_embedded_file;\n");
	int n = 0;
	for (int i = first_file; i < argc; i++, n++) {
		FILE *f = fopen(argv[i], "rb");
		if (!f) { perror(argv[i]); return 1; }
		fprintf(o, "static const unsigned char d%d[] = {", n);
		int c; long len = 0;
		while ((c = fgetc(f)) != EOF) {
			if (len % 20 == 0) fputs("\n", o);
			fprintf(o, "%d,", c);
			len++;
		}
		fprintf(o, "\n0};\n");
		fclose(f);
	}
	fprintf(o, "const pf_embedded_file %s_files[] = {\n", prefix);
	for (int i = first_file, k = 0; i < argc; i++, k++)
		fprintf(o, "  {\"%s\", d%d, sizeof(d%d) - 1},\n", basename_of(argv[i]), k, k);
	fprintf(o, "};\nconst size_t %s_count = %d;\n", prefix, n);
	fclose(o);
	return 0;
}
